#!/bin/bash

## Get battery info
BATTERY="$(acpi | awk -F ' ' 'NR==1 {print $4}' | tr -d \%,)"
CHARGE="$(acpi | awk -F ' ' 'NR==1 {print $3}' | tr -d \,)"

main() {
	if [[ ($CHARGE = *"Charging"*) && ($BATTERY -lt "100") ]]; then
		echo "images/icons/charge.svg"
	elif [[ $CHARGE = *"Full"* ]]; then
		echo "images/icons/battery-4.svg"
	else
		if [[ ($BATTERY -lt 100) && (($BATTERY -gt 70) || ($BATTERY -eq 70)) ]]; then
			echo "images/icons/battery-4.svg"
		elif [[ ($BATTERY -lt 70) && (($BATTERY -gt 45) || ($BATTERY -eq 45)) ]]; then
			echo "images/icons/battery-4.svg"
		elif [[ ($BATTERY -lt 45) && (($BATTERY -gt 25) || ($BATTERY -eq 25)) ]]; then
			echo "images/icons/battery-2.svg"
		elif [[ ($BATTERY -lt 25) && (($BATTERY -gt 0) || ($BATTERY -eq 0)) ]]; then
			echo "images/icons/battery-1.svg"
		fi
	fi
}

if [[ $1 == '--icon' ]]; then
	main
elif [[ $1 == '--perc' ]]; then
	echo "${BATTERY}%"
fi
