#!/bin/bash

sleep 0.5

CHARGE="$(acpi | awk -F ' ' 'NR==1 {print $3}' | tr -d \,)"

## Get battery info
BATTERY="$(acpi | awk -F ',' 'NR==1 {print $2}' | tr -d \%)"
REMAINING="$(acpi | awk -F ',' 'NR==1 {print $3}')"

icon=""

get_icon() {
	if [[ ($CHARGE = *"Charging"*) ]]; then
		icon="images/icons/battery-charge.svg"
	elif [[ $CHARGE = *"Full"* ]]; then
		icon="images/icons/battery-4.svg"
	else
		if [[ (($BATTERY -gt 75) || ($BATTERY -eq 75)) ]]; then
			icon="images/icons/battery-4.svg"
		elif [[ ($BATTERY -lt 75) && (($BATTERY -gt 50) || ($BATTERY -eq 50)) ]]; then
			icon="images/icons/battery-3.svg"
		elif [[ ($BATTERY -lt 50) && (($BATTERY -gt 25) || ($BATTERY -eq 25)) ]]; then
			icon="images/icons/battery-2.svg"
		elif [[ ($BATTERY -lt 25) && (($BATTERY -gt 0) || ($BATTERY -eq 0)) ]]; then
			icon="images/icons/battery-1.svg"
		fi
	fi

    if [ ! -f /tmp/battery-icon-log ]; then
        touch /tmp/battery-icon-log
        chmod 666 /tmp/battery-icon-log
    fi

    echo "${icon}" >> /tmp/battery-icon-log
}


if [[ $1 == --power-cord ]]; then 
    if $2; then 
        CHARGE="Charging"
    fi
elif [[ $1 == --perc ]]; then
    echo "${BATTERY}%"
elif [[ $1 == --remain ]]; then
    echo "${REMAINING}"
fi

get_icon
